name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: forward-lead-354606
      IMAGE_LIST: 'docker_compose_ubuntu,nginx,mysql'
      FILE_PATH: /script/gcp.sh
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        id: build_stack
        run: docker-compose up -d
        continue-on-error: true

      - name: Check on failures
        if: steps.build_stack.outcome != 'success' 
        run: |-
          echo "Workflow failed!!!"
          exit 1


      - name: Check on success
        if: steps.build_stack.outcome == 'success' 
        run: |-
          echo "Workflow successfully!!!"
          exit 0

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_GCP }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
         gcloud auth configure-docker --quiet
    
      - name: Push Docker Image to Container Registry (GCR)
        run: |-
          IFS="," read -a IMAGE_array <<< ${{ env.IMAGE_LIST }}
          for IMAGE in "${IMAGE_array[@]}" ; do
           docker tag ${IMAGE}:latest gcr.io/$PROJECT_ID/${IMAGE}:latest
           docker push gcr.io/$PROJECT_ID/${IMAGE}:latest
          done

      - name: Deploy Docker image
        run: gcloud compute instances create test_vm \
           --zone=us-central1-a \
           --image-project=debian-cloud \
           --image-family=debian-10 \
           --metadata-from-file=startup-script=$FILE_PATH
        
      
 