name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: testimage10
      PROJECT_ID: forward-lead-354606
      ZONE:  us-central1
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        id: build_stack
        run: docker-compose up -d
        continue-on-error: true

      - name: Check on failures
        if: steps.build_stack.outcome != 'success' 
        run: |-
          echo "Workflow failed!!!"
          exit 1


      - name: Check on success
        if: steps.build_stack.outcome == 'success' 
        run: |-
          echo "Workflow successfully!!!"
          exit 0

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_GCP }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
         gcloud auth configure-docker --quiet
         gcloud auth configure-docker $ZONE-docker.pkg.dev --quiet
    
      - name: Push Docker Image to Container Registry (GCR)
        run: |-
         docker tag docker_compose_ubuntu:latest gcr.io/$PROJECT_ID/docker_compose_ubuntu:latest
         docker tag nginx:latest gcr.io/$PROJECT_ID/nginx:latest
         docker tag mysql:latest gcr.io/$PROJECT_ID/mysql:latest
         docker push gcr.io/$PROJECT_ID/docker_compose_ubuntu:latest
         docker push gcr.io/$PROJECT_ID/nginx:latest
         docker push gcr.io/$PROJECT_ID/mysql:latest
 