name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        id: build_stack
        run: docker-compose up -d
        continue-on-error: true

      - name: Check on failures
        if: steps.build_stack.outcome != 'success' 
        run: -|
          echo "Workflow failed!!!"
          exit 1

      - name: Check on success
        if: steps.build_stack.outcome == 'success' 
        run: | 
          echo "Workflow successfully!!!"
          exit 0

    
