name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: forward-lead-354606
      IMAGE1: docker_compose_ubuntu
      IMAGE2: nginx
      IMAGE3: mysql
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        id: build_stack
        run: docker-compose up -d
        continue-on-error: true

      - name: Check on failures
        if: steps.build_stack.outcome != 'success' 
        run: |-
          echo "Workflow failed!!!"
          exit 1


      - name: Check on success
        if: steps.build_stack.outcome == 'success' 
        run: |-
          echo "Workflow successfully!!!"
          exit 0

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_GCP }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker Client
        run: |-
         gcloud auth configure-docker --quiet
    
      - name: Push Docker Image to Container Registry (GCR)
        run: |-
         docker tag $IMAGE1:latest gcr.io/$PROJECT_ID/$IMAGE1:latest
         docker tag $IMAGE2:latest gcr.io/$PROJECT_ID/$IMAGE2:latest
         docker tag $IMAGE3:latest gcr.io/$PROJECT_ID/$IMAGE3:latest
         docker push gcr.io/$PROJECT_ID/$IMAGE1:latest
         docker push gcr.io/$PROJECT_ID/$IMAGE2:latest
         docker push gcr.io/$PROJECT_ID/$IMAGE3:latest
 