name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        id: build_stack
        run: docker-compose up -d

      
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print successfully if build work
        if: steps.build_stack.outputs.exit_code == 0
        run: echo "Workflow successfully ran"
      
      - name: Print failed if build failed
        if: steps.build_stack.outputs.exit_code == 1
        run: echo "Workflow failed!!!""

