name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        id: test
        run: docker-compose up -d

      - name: Create artifact of test coverage
        if: steps.test.outputs.exit_code == 0
        run: echo "!!!!!!!!!!!!!!!!"
      
      - name: no artifact of test coverage
        if: steps.test.outputs.exit_code =! 0
        run: echo "@@@@@@@@@@@@@@@@@@@@@"

