name: Docker Compose Actions Workflow
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build Docker Image
        run: |
        if [[ $? -ne 0 ]] ; then
echo "SQL query failed"
    exit 1
else
    echo "SQL query success!"
fi

   